### ISSUE TITLE
Double underscores

### ISSUE THREAD

**Issue by sergio-bershadsky** [LPgenerator/django-db-mailer#1]
Хотелось бы услышать мнение автора на тему обильного использования двойных подчеркиваний  особенно интересуют методы классов которые фактически не участвуют в наследование. Чем мотивируется такое желание сделать все методы приватными членами класса?

**Comment by gotlium** [comment]
Методы приватные и не должны вызываться из вне.

**Comment by sergio-bershadsky** [comment]
Это же питон если мне надо будет, я смогу его вызвать, чем не угодили одинарные подчеркивания?

**Comment by gotlium** [comment]
Не вижу смысла вести подобную дискуссию, тем более здесь.

**Comment by sergio-bershadsky** [comment]
А где удобней?

**Comment by gotlium** [comment]
Дело не в удобстве, а в основе. Для чего нужны приватные и публичные методы?
Ответ прост: что бы не перегружать других программистов деталями реализации. Это считается хорошей практикой. Какие-то более важные вещи можно обсуждать gtalk:)
