### ISSUE TITLE
What version of Django should be supported

### ISSUE THREAD

**Issue by ruscoder** [LPgenerator/django-db-mailer#113]
What version of Django should be supported? 

Can we drop support of Django 1.4 and switch to support only 1.8+ Django versions or even only LTS?
Anyway, old versions will be still available in PyPi and can be used for users with old Django versions.

**Comment by deniskabalkin** [comment]
Let's switch to 1.8+. We can discuss only LTS support  later.

**Comment by ruscoder** [comment]
Ok. I've removed all code for Django version <1.8 (including south migrations).
