### ISSUE TITLE
remove redundant setting

### ISSUE THREAD

**Issue by ilstreltsov** [LPgenerator/django-db-mailer#116]
If I correctly understood the need of use CELERY_TASK_DECORATOR_PATH setting, seems like [shared_task](http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html?highlight=shared_task#using-the-shared-task-decorator) decorator  is a good and correct replacement for this setting. 

not tested
```
try:
    from celery import shared_task as task
except ImportError:
    try:
        from celery import task
    except ImportError:
        ...
```

**Comment by ruscoder** [comment]
@ilstreltsov Hello! Thank you for the advice!
