### ISSUE TITLE
python 3.7 django 2.1

### ISSUE THREAD

**Issue by mhndev** [LPgenerator/django-db-mailer#118]
I'm getting following error in python 3.7 , django 2.1.

File "C:\Projects\Shenoto\MessageServer\venv\lib\site-packages\dbmail\models.py", line 113, in MailFromEmail
    blank=True, null=True, default=None)
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by ruscoder** [comment]
Hello @mhndev! It seems you are using the previous version from PyPI. But Django 2+ support was added only in a master branch.  
Soon we'll publish a new version into PyPI.

**Comment by mhndev** [comment]
Thanks
