### ISSUE TITLE
Как вставить ссылки?

### ISSUE THREAD

**Issue by AlexDev1** [LPgenerator/django-db-mailer#12]
Как можно вставить ссылки или урл картинки?

**Comment by gotlium** [comment]
это всего лишь html. все так же.

**Comment by AlexDev1** [comment]
Я имею ввиду динамические ссылки, например шаблон для рассылки в блоге куда можно передавать название, описание урл, картинку, и в дальнейшем использовать один шаблон, или нужно под каждую статью создавать новый шаблон?

**Comment by gotlium** [comment]
логичнее один. это всего лишь темплейты. можно даже инклудить оформление с файловой системы.

**Comment by AlexDev1** [comment]
дак да конечно, понял что это тайнмс режет параметры например {{ img_url }} на  %7B%7B%20img_url%20%7D%7D%20,

**Comment by gotlium** [comment]
он опционален

**Comment by AlexDev1** [comment]
как тогда вызвать send_db_mail чтобы инклудить с файловой системы?

**Comment by gotlium** [comment]
ничего не меняется. шаблон:

```
{% extends 'mail/base_html.html' %}
{% block content %}
...
{% endblock content %}
```

**Comment by AlexDev1** [comment]
good!

**Comment by vosi** [comment]
как насчет вынести екстенды на более высокий уровень
типа базы данных лейаутов?
и выбора онных в шаблоне письма

а то по опыту - простым юзерам не дружелюбно

**Comment by gotlium** [comment]
для начала надо посмотреть на все это. во вторых лично сам не вижу в этом смысла. то есть обычному человеку ваще пофиг. ему поправить только одну букву/слово/предложение. система должна быть простой и в тоже время концептуально не сильно различаться от самой джанго.

**Comment by vosi** [comment]
ну вот про обычных человеков - у меня клиенты бояться туда лезть, и все равно просят поправить

**Comment by vosi** [comment]
они привыкли к {{ }} но их пугают {% %}

**Comment by gotlium** [comment]
покажите пример того что хочется. можете самостоятельно реализовать что-то, прислать пул реквест) можно обсудить как да что. сложно говорить о том, чего еще нет)

**Comment by gotlium** [comment]
на сколько я понимаю, есть желание и необходимость иметь дополнительную модель. в ней задаем базовый html шаблон, добавляем заголовок шаблона. выбираем базовый шаблон при создании/редактировании шаблона сообщения.

**Comment by vosi** [comment]
да да, именно так
я могу запилить и запушить
у меня для одного проекта это в планах
просто уточняю, надо ли вообще такая штука
или форкать )))

**Comment by gotlium** [comment]
в целом идея нравится. базовый шаблон лучше все же править так же в БД:)
главное что бы кеш работал как положено. 1 запрос, после все в кеше. запросов к бд нет.

**Comment by gotlium** [comment]
@vosi когда уже?) а то могу и сам запилить. как раз выдалось свободное времечко)

**Comment by vosi** [comment]
честно, не совсем скоро, сейчас совсем полно работы, и по проекту эту штуку понизили до ранга "какнить потом" (((

**Comment by gotlium** [comment]
значит сам подумаю над реализацией и сделаю в ближайшем будущем:)
