### ISSUE TITLE
Delete selected Mail logs 403 Forbidden

### ISSUE THREAD

**Issue by ghost** [LPgenerator/django-db-mailer#14]
при попытке удалить несколько записей из лога получаю  403 Forbidden

при этом если зайти в конкретный лог то по отдельности все удаляется

**Comment by gotlium** [comment]
так задумано. массовое удаление разрешено только супер юзеру. https://github.com/LPgenerator/django-db-mailer/blob/master/dbmail/admin.py#L192
можно запретить и отдельно удалять записи.

**Comment by ghost** [comment]
так я и есть супер юзер

Superuser status
Designates that this user has all permissions without explicitly assigning them.

**Comment by gotlium** [comment]
ссылка на код выше. возможно что-то там не так?!

**Comment by ghost** [comment]
ок пасиб
