### ISSUE TITLE
Required South

### ISSUE THREAD

**Issue by yeralin** [LPgenerator/django-db-mailer#19]
Hi,

In your installation tutorial it says that South is required. The problem is that Django keeps sending me Warnings about South deprecation in Django 1.9. Are you going to do something with it?

Я читал ваш пост на хабре, и у меня еще один личный вопрос:

Смогу ли я использовать вашу батарейку вместе с django-ses?

Best,
Daniyar Yeralin

**Comment by gotlium** [comment]
Hi,
yes, battery can be used with South (Django==1.4) and with Django==1.8 (Native). I can't say about 1.9. But I think you can use without any problems. We are support two part of migrations. South and native. You can see it at project tree https://github.com/LPgenerator/django-db-mailer/tree/master/dbmail.

Что касается django-ses: могу сказать что да, вы сможете. 
Выбор бекенда всегда остается на усмотрение разработчика.
В инструкции или в статье есть упоминание postmark-а. 
Работает без нареканий поверх http апи.
Знаю точно, что в одном из проектов используется бекенд aws.

**Comment by yeralin** [comment]
Спасибо большое. Написал на Русском и Английском, потому что не знал, кто будет читать тикет :)

**Comment by gotlium** [comment]
Ничего страшного) На каком пишут - на том и ответ. 
Настоятельно советую использовать ветку developement, если хотите последние вкусняхи и исправления ошибок. 
Не найду времени перевести все в мастер и отправить в pypi. Могу лишь сказать что уже скоро:)

**Comment by gotlium** [comment]
@yeralin удалось ли интегрировать с Django 1.9?

**Comment by gotlium** [comment]
Поддержка Django 1.9 уже в development ветке.
