### ISSUE TITLE
Как работать с группами 

### ISSUE THREAD

**Issue by AlexDev1** [LPgenerator/django-db-mailer#29]
Не могу найти в документацию как работать с группами, в приложении есть группы в группах есть инлайны имя и адрес,  какие либо апи для работы с группами?

**Comment by AlexDev1** [comment]
Посмотрел в коде отправлять можно:
['user1@example.com', 'user2@example.com'] or string Mail group slug
    recipient='user1@example.com',
тогда в одно сообщение вставить всю группу адресов, верно?

**Comment by gotlium** [comment]
```
# ['user1@example.com', 'user2@example.com'] or string Mail group slug
```

**Comment by gotlium** [comment]
пример простой. есть у вас к примеру 2 группы: админы/саппорт
создаешь 2 группы. вбиваешь мыло/телефон или что-то еще
и отправляешь send_db_mail('mail-group', ..some part...)

**Comment by gotlium** [comment]
у нас это используется как групповое уведомление разных отделов
