### ISSUE TITLE
_get_context method in mail.py should use context._meta.model_name instead context._meta.module_name

### ISSUE THREAD

**Issue by Nekmo** [LPgenerator/django-db-mailer#30]
module_name parameter is removed in 1.8 https://code.djangoproject.com/ticket/19689

This causes a fault in my program:

```
Exception Type: AttributeError at /coms/send-email/
Exception Value: 'Options' object has no attribute 'module_name'
```

Please fix the problem.

**Comment by gotlium** [comment]
I don't have a time. You can fix it by you're self at development branch. thanks.

**Comment by gotlium** [comment]
@skhaylov, thanks.

**Comment by gotlium** [comment]
`pip install django-db-mailer==2.3a1`
