### ISSUE TITLE
Different text and html message

### ISSUE THREAD

**Issue by katomaso** [LPgenerator/django-db-mailer#41]
Hi,
it would be very nice to have the possibility to define textual and HTML message separately. You are using the function `dbmail.utils.clean_html` to strip out the HTML tags but this is insufficient in case you want a rich and nice HTML with images and stuff but your textual message would look weird if those images were removed. 

I think that adding another field `body` next to the HTML `message` would do the job.

**Comment by gotlium** [comment]
Hi, possible we can change `dbmail.utils.clean_html` functionality. Can you show examples with images result. 
If we add a text body field, then we need to clean text from html to text using js on admin.

**Comment by gotlium** [comment]
@vosi what you think about this idea?

**Comment by katomaso** [comment]
Hi, I was thinking about offering the possibility to fully customize non-html message. But when I think about it again then not many people would use it. I saw it on myself when I imagined I should rewrite all my email templates.
