### ISSUE TITLE
Can we use aws sqs as queue ? If yes how?

### ISSUE THREAD

**Issue by sagarg1988** [LPgenerator/django-db-mailer#57]
I want to use aws sqs as a queue, and I didn't get any issue or any use case around it . Can some give me the solution for the same ?

**Comment by gotlium** [comment]
I think you can write your own backend to celery, and use it as queue broker. 
Or you can create plugins mechanism for queue. It will be great to use different queues such RQ/Celery/AWS or anything else.

**Comment by gotlium** [comment]
Amazon SQS is implemented on celery http://docs.celeryproject.org/en/latest/getting-started/brokers/sqs.html . 
Celery configuration for `dbmail` available at the docs http://django-db-mailer.readthedocs.io/settings.html#optional-settings
