### ISSUE TITLE
Is it any requirement of celery to install along with dbmail ?

### ISSUE THREAD

**Issue by sagarg1988** [LPgenerator/django-db-mailer#58]
I have install dbmail , when i try to run the code ,I get this error 
`'module' object is not callable`

and which shows me the error near line 
`if celery_supported() and use_celery is True:` line number 45

and 
`import dbmail.tasks` line number 24

Can anyone tell me what is wrong ?

**Comment by gotlium** [comment]
Show me a full python stack trace

**Comment by sagarg1988** [comment]
Sorry I got the problem, It was my typo.
