### ISSUE TITLE
How does Mail Base Template and Message(Body) works?

### ISSUE THREAD

**Issue by sagarg1988** [LPgenerator/django-db-mailer#59]
Is there any description or documentation of how to use Mail Base Template and when to use Message or Body instead?
I tried to set a base template but then my message is ignored completely. Should only one of these be used? In what scenario ?What is the purpose of giving both of these fields separately?

Please let me know or link to any documentation 
Thanks

**Comment by gotlium** [comment]
This functionality is not documented, but is it have very simple API. You can specify any block on Base templates, choose it in the Message. In fact, this is equal to {% extends "base.html" %}

**Comment by sagarg1988** [comment]
okay Thanks
