### ISSUE TITLE
Django >=1.9, broken Test template and Browse vars

### ISSUE THREAD

**Issue by last-partizan** [LPgenerator/django-db-mailer#76]
From release notes:

> The URL of the admin change view has been changed (was at /admin/<app>/<model>/<pk>/ by default and is now at /admin/<app>/<model>/<pk>/change/)

And `static/dbmail/admin/dbmail.js` contains hardcoded urls to `./sendmail/` and `./sendmail/apps/` which now results in 404.

**Comment by jab3z** [comment]
I have the same issue

**Comment by gotlium** [comment]
Fixed now on development branch http://take.ms/W2s6p
