### ISSUE TITLE
Django 1.10 support?

### ISSUE THREAD

**Issue by jeffcjohnson** [LPgenerator/django-db-mailer#81]
Hello,

I'm hoping to use django-db-mailer in my project but I am using Django 1.10 and it looks like only 1.8 is supported.  

I was wondering if there are plans to add support for 1.10?   

I might be able to help with that effort but since I've never used django-db-mailer I don't know if I'm the best person for that.

Thanks!

**Comment by gotlium** [comment]
Hi, we are supporting Django 1.10. You are have a problems with 1.10?

**Comment by jeffcjohnson** [comment]
Oh, that's excellent.  I'm seeing this problem which I believe is because django.conf.urls.patterns was removed in 1.10.  This is with django-db-mailer 2.3.13

```
site-packages/dbmail/urls.py", line 3, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name 'patterns'
```

**Comment by gotlium** [comment]
PR?))) But we are supporting Django 1.4/1.8/1.11 (this is new LTS)
`urls.py` on most cases is not used. All problems are will be solved when our users this case will be used on new versions on Django or Python.

**Comment by jeffcjohnson** [comment]
PR #82

**Comment by gotlium** [comment]
Thanks. Merged:)
