### ISSUE TITLE
Base template does not have <html> tag, included template does

### ISSUE THREAD

**Issue by jeffcjohnson** [LPgenerator/django-db-mailer#85]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The base template doesn't have html and head tags but the child template does.  This puts the html and head tags in the middle of the document.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create a base template and use it in an email template, then print the results (see below).

**What is the expected behavior?**
If automatically inserting html, head and body tags is expected, the base template should do it and if and only if there is no base template, the child template should insert html, head and body tags.

**Which versions of DbMail, Django and which Python / OS are affected by this issue? Did this work in previous versions of DbMail?**
django-db-mailer (2.3.13) - this is my first time trying the software.

Look for the html, head and body tags in the generated email:
```
--===============5259964975024812885==
MIME-Version: 1.0
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: 7bit

<p>This is the start of the <strong>base template.</strong></p>
<p>The content tag will follow this.</p>
<p><html>
<head></head>
<body>
<p>This is the start of the Mail Template.</p>
<p><strong>Hello Jane Doe!</strong></p>
<p>This is the end of the Mail Template.</p>
</body>
</html>
</p>
<p>The content tab was above this.</p>
<p>This is the end of the <strong>base template.</strong></p><table bgcolor="white"><tr><td><font size="-1" color="black"><img src="http://example.com/dbmail/mail_read_tracker/IjE0ODU0Nzg3MzAuMzI5NTMwLTQ2ZDIzMjY5LWQxMWYtNDkyYi04MzY2LTlhYzZiNjRiN2EzMCI:1cWusM:5G8euYXpziXQolvfQv8KEm578hI/" width="16" height="16" alt="" title="" border="0"></font></td></tr></table></center>
--===============5259964975024812885==--
```

**Comment by gotlium** [comment]
Hi, can you show how you are using base template. Give me examples.

**Comment by jeffcjohnson** [comment]
I have a MailBaseTemplate like this:

```
This is the start of the base template.
The content tag will follow this.
{{content}}
The content tab was above this.
This is the end of the base template.
```

And a MailTemplate like this:

```
This is the start of the Mail Template.
Hello {{user.first_name}} {{user.last_name}}!
This is the end of the Mail Template.
```

The MailTemplate has the MailBaseTemplate selected.  

I assume the idea is to put common headers and footers into the MailBaseTemplate and apply them to all of the MailTemplates.

**Comment by gotlium** [comment]
This problem because you are using `premailer` battery. You can remove this package, and check again.

**Comment by jeffcjohnson** [comment]
Hi, thanks for the help.

Removing premailer and then saving the MailTemplate again did remove the html, head and body tags from MailTemplate.message.  For anyone following this, the tags were saved to the database so removing premailer alone won't fix it, you have to re-save the template.
