### ISSUE TITLE
Альтернативная DB

### ISSUE THREAD

**Issue by kshishkin82** [LPgenerator/django-db-mailer#86]
Есть ли возможность указать Django-db-mailer какую  DB использовать ?
Допустим, если в Django несколько DATABASES,  то было бы замечательно иметь возможность выбрать какую из DB использовать. 

Собственно проблема лично у нас в следующем: одни и те-же шаблоны используются на разных серверах в разных инстансах одного и того же проекта. Соответственно у них разные базы данных. Основная проблема с Db-mailerом это синхронизация шаблонов писем. Пока было 3-4 сервера делали это вручную, сейчас серверов 10+ и делать это в ручном/полу ручном режиме становится не удобно. Если бы можно было бы указать какой-то отдельный DB backend для mailerа то мы бы вынесли всю базу для этой подсистемы в один сервере и остальные сервера "питались" бы данными оттуда.

**Comment by gotlium** [comment]
добрый день, не совсем понимаю почему у вас проект использует разные БД, разве что вы для каждого клиента создаете отдельный сервер. но в целом проблем не вижу. можно к примеру создать PR, и добавить `using`, но можно использовать route-инг, ведь джанга позволяет сделать нечто подобное. уже в роутере можно по app_label выбрать направление.

**Comment by kshishkin82** [comment]
Вопрос закрыт, да, я тупанул. Нужно просто роутинг сделать. Спасибо за подсказку.
