### ISSUE TITLE
Using celery without djcelery

### ISSUE THREAD

**Issue by DimaKudosh** [LPgenerator/django-db-mailer#87]
Hello, 
DB mailer works with celery only when djcelery is installed. But with latest version of celery it's possible to use celery with django without this library. How I can use db-mailer with celery without djcelery installed?

**Comment by gotlium** [comment]
Hi, can you show errors when celery is not installed?

**Comment by DimaKudosh** [comment]
It doesn't raise any error, it just ignore use_celery parameter when djcelery isn't installed. In your __init__.py you have following code:
```python
def celery_supported():
    try:
        from dbmail import tasks
        if not app_installed('djcelery'):
            raise ImportError
        return True
    except ImportError:
        return False
```
So celery_supported will always return False if you haven't djcelery, even if you use celery in your project.

**Comment by gotlium** [comment]
Can you try disable this code, and check how app working without `djcelery`?

**Comment by DimaKudosh** [comment]
After disabling this code it works fine, so problem in this function.

**Comment by gotlium** [comment]
what about queue and another functionality?

**Comment by gotlium** [comment]
and additional question: how we can check `celery` configuration without `djcelery` app?

**Comment by DimaKudosh** [comment]
I setup celery using this tutorial from docs [http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html](http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html). Then I run celery using this command `celery -A project worker -l info -Q default`. Also in django-celery repo I found this warning 

> THIS PROJECT IS ONLY REQUIRED IF YOU WANT TO USE DJANGO RESULT BACKEND AND ADMIN INTEGRATION

 So I didn't install it because admin integration and results not important for me.
