### ISSUE TITLE
Python 3 & Django 1.8

### ISSUE THREAD

**Issue by ad-lebedev** [LPgenerator/django-db-mailer#9]
Приветствую!
Планируется ли совместимость с сабжем? И если да, то когда?

**Comment by gotlium** [comment]
Доброго времени суток. В todo есть. Но это не раньше 3-го релиза батарейки. Если есть возможность и свободное время, то pull-request приветствуется :) 
кстати батарейка совместима с веткой 1.8

**Comment by gotlium** [comment]
первоначальная поддержка Python 3.4 (https://github.com/LPgenerator/django-db-mailer/tree/py3)
пробуйте. отписывайтесь.
