### ISSUE TITLE
Error: <SimpleLazyObject: <User: xx>> is not JSON serializable

### ISSUE THREAD

**Issue by hongquan** [LPgenerator/django-db-mailer#93]
When I call `send_db_mail` with keyword argument `user=request.user` and no `use_celery`, there is error:

```
TypeError: <SimpleLazyObject: <User: xx>> is not JSON serializable
```

I think it is because `send_db_mail` by default handover the task to Celery, and hence, the argument has to be serialized. But while other argument are string and dict, which are serializable, the `user` is not.

My environment: Django 1.11, django-db-mailer 2.3.17, Python 3.5, Ubuntu 17.04.

Do you think we should let pass user_id instead?

**Comment by hongquan** [comment]
Ah no, actually, the `context` argument is a `dict` and often contains Django model object, which is also not serializable!

**Comment by gotlium** [comment]
> TypeError: <SimpleLazyObject: <User: xx>> is not JSON serializable

Change celery serializer on your settings.py

    CELERY_TASK_SERIALIZER = 'pickle'


> Do you think we should let pass user_id instead?

Yes. It's a good idea and best practice, when you working with celery.
