### ISSUE TITLE
GeoIP2 in Tracking

### ISSUE THREAD

**Issue by lcd1232** [LPgenerator/django-db-mailer#98]
Request a feature:

Right now only [GeoIP](https://github.com/LPgenerator/django-db-mailer/blob/master/dbmail/models.py#L721) support in this package but since django 1.9 GeoIP is deprecated and now using [GeoIP2](https://docs.djangoproject.com/en/1.11/ref/contrib/gis/geoip2/). I can implement this feature and for backward compatibility I can add new settings for choosing between GeoIP and GeoIP2.

**Comment by gotlium** [comment]
Hi, it's a good idea)
